### PR TITLE
Remove Google Analytics support

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by kalvdans** [comment]
Yay, finally! Reopen https://github.com/tschoonj/xraylib/issues/143 ?

**Comment by tschoonj** [comment]
Why?

**Comment by kalvdans** [comment]
Since the issue is about adding tracking, and now tracking is removed.

**Comment by tschoonj** [comment]
I'll add a note to it, but don't think it should be reopened.

**Pull request merged**
