### PR TITLE
Anomalous scattering factors: switch to EPDL97

### PR DESCRIPTION
**Pull request by tschoonj**
@srio
@mdw771
@altaskier

I have decided to give EPDL97 a go as the 30 keV limit in the Henke dataset (see #54) is a dealbreaker for me.
Feel free to test this dataset and let me know what you think about this.

### CODE REVIEW

**Comment by altaskier** [comment]
Hi Tom - I think this should be OK.  I’ll do a plot of the differences of Henke and EPDL97, but I think EPDL is way better than having the glitches in Kissel.

CJ

**Comment by tschoonj** [comment]
Thanks Chris!

I will be on holidays for the next two weeks. When I am back I will make a new xraylib release, assuming no other major issues pop up in the meantime...

**Comment by tschoonj** [comment]
@mdw771 can you please confirm if EPDL97 works out for you?

I would like to merge this in as soon as possible and make a new release

Thanks!

**Comment by mdw771** [comment]
Oops sorry for some reason I didn't get notification for this thread. 

Just ran the same test for this release. Things are looking good. I can see a f2 bump at Fe K edge but I guess it won't be a big issue. 
screenshot 2017-09-11_10-07-41

Thanks a lot for the update!

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
