### PR TITLE
Fix build with numpy v2

### LINKED ISSUE #239: Failed to build with numpy v2
Trying to build xraylib with numpy v2 and cython 3.0.10 I encountered the following error:

```
[100/162] Generating python/xraylib_np_c with a custom command
FAILED: python/xraylib_np.c 
envs/py312/bin/cython -X language_level=3,boundscheck=False,wraparound=False,cdivision=True ../python/xraylib_np.pyx -o python/xraylib_np.c

Error compiling Cython file:
------------------------------------------------------------
...
P5_SHELL = xrl.P5_SHELL
Q1_SHELL = xrl.Q1_SHELL
Q2_SHELL = xrl.Q2_SHELL
Q3_SHELL = xrl.Q3_SHELL

def AtomicWeight(np.ndarray[np.int_t, ndim=1] Z not None):
                               ^
------------------------------------------------------------

src/xraylib/python/xraylib_np.pyx:1494:31: Invalid type.
[101/162] Generating src/xrayglob_inline.c with a custom command
ninja: build stopped: subcommand failed.
```

`int_t` is no longer defined by numpy in [`numpy.__init__.pxd`](https://github.com/numpy/numpy/blob/main/numpy/__init__.pxd), while it was with v1.x: https://github.com/numpy/numpy/blob/v1.26.5/numpy/__init__.pxd#L712

### PR DESCRIPTION
**Pull request by t20100**
This PR proposes 2 changes:
- Use `cimport numpy as cnp` instead of `np` to differentiate `import` from `cimport` as suggested in https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html#adding-types
- Replace the use of `np.int_t` type by `long` to restore the typed defined in numpy v1: see https://github.com/numpy/numpy/blob/v1.26.5/numpy/__init__.pxd#L258 and https://github.com/numpy/numpy/blob/v1.26.5/numpy/__init__.pxd#L712).
- 
closes #239

### CODE REVIEW

**Comment by tschoonj** [comment]
Thanks for opening the PR, I will take a look at this soon

**Comment by t20100** [comment]
CI failure on macos may be related to the change of `macos-latest` which is now `macos-14` which runs on `arm64`.

**Comment by tschoonj** [comment]
@t20100 I think this is ready for a merge now?

I have deployed your patch to Conda-forge [already](https://github.com/conda-forge/xraylib-feedstock/pull/48), so conda users will be able to use numpy 2 already.

**Comment by t20100** [comment]
> I think this is ready for a merge now?

It's OK for me!

Thanks for already having deployed the fix on conda!

**Pull request merged**
