### PR TITLE
Pascal

### PR DESCRIPTION
**Pull request by wormy69**
Simplified Pascal bindings and tested with Delphi and Lazarus under Windows 7 and OSX Yosemite

### CODE REVIEW

**Comment by tschoonj** [comment]
Hi Matthew,

Looks good. Can you explain me why the last commit is necessary (the underscores on Mac OS X)? Does this work with both FPC and Delphi?

**Comment by wormy69** [comment]
The additional underscore is only needed by the Delphi compiler

http://docwiki.embarcadero.com/RADStudio/XE7/en/Shared_Libraries_for_Mac_OS_X

The underscore is handled automatically by the FPC compiler / linker and so is not needed

To this end I use the MACOS symbol that is defined for Delphi under OSX but not for FPC (which uses DARWIN).

The binding has been tested and works with both Delphi and FPC. I just happened to work through checking in the binding to Git before trying to build the universal library and then finding the need for the underscore in Delphi on OSX.

Matthew

**Comment by tschoonj** [comment]
Thanks for the work, I pulled it in.

One thing though: you should set up your name and email as said in https://help.github.com/articles/set-up-git/#setting-up-git
Unfortunately, now you show up as 'unknown' for these commits :-(

**Comment by wormy69** [comment]
Will do and not to worry, I added my name along with yours at the top of the xraylib.pas file.

I setup GitHub but not the Git software I guess.

Matthew

**Comment by wormy69** [comment]
And thanks for you for maintaining this project – it’s a valuable resource for the X-ray community and so I am only too happy to make some contributions.

Matthew

**Comment by tschoonj** [comment]
You’re most welcome.

Will continue to maintain it as long as I can.

In a couple of weeks or months I will get back in touch when the time comes to start packaging for the next release.
I should have a look at the partial PE cross sections first, as they create some kind of internal inconsistency with regard to the total PE cross sections.

Best,

Tom


Dr. Tom Schoonjans
Research Fellow

Bundesanstalt für Materialforschung und -prüfung (Federal Institute for Materials Research and Testing)
Richard-Willstätter-Strasse 11, 12489 Berlin
Germany

Telephone +49 (0) 30-8104-5612

Tom.Schoonjans@bam.de<mailto:Tom.Schoonjans@bam.de>
www.bam.de


On 02 Apr 2015, at 19:00, Matthew Wormington <notifications@github.com<mailto:notifications@github.com>> wrote:

And thanks for you for maintaining this project – it’s a valuable resource for the X-ray community and so I am only too happy to make some contributions.

Matthew

**Pull request merged**
